name: Docker Image CI

on:
    push:
        branches:
            - main
    pull_request:
        types: [closed]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-@v1

            - name: Build and Push Docker Image to Dockerhub
              uses: docker/build-push-action@v2
              with:
                context: ./api/
                file: ./api/Dockefile
                push: true
                tags: |
                    rzbyn/parking_app:latest
                    rzbyn/parking_app:${{ github.sha }}
                dockerfile: ./api/Dockerifle
              env:
                DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
